### ISSUE TITLE
Agregar logo de la católica en la sección de sponsors

### ISSUE THREAD

**Issue by joedayz** [perujug/jconfperu#3]
La universidad católica nos dará el local de OPEN PUCP para el 2 de diciembre. Hay que colocar el logo de ellos y de ser posible agrandar un poco esos logos porque se ve muy chico también el de BCP.

![Screenshot 2023-10-14 at 18 25 58](https://github.com/perujug/jconfperu/assets/1118135/25bccf32-14c0-4db6-9ecb-b123953df02f)

**Comment by czelabueno** [comment]
Agregado en este PR https://github.com/perujug/jconfperu/pull/9
