### ISSUE TITLE
Agregar en meetup.com el evento para que se registren a la JCONF PERU 2023

### ISSUE THREAD

**Issue by joedayz** [perujug/jconfperu#4]
Estimados, hay que crear el evento de PERUJUG en la página de meetup.com 

https://www.meetup.com/peru-java-user-group/

Solicitar el permiso a Jose para invitarlos y puedan crear el evento.

**Comment by czelabueno** [comment]
Ya esta hecho, ha tenido que llegar un email a todos los registrados a nuestra pagina en meetup.com

https://www.meetup.com/peru-java-user-group/events/296799025/
