### ISSUE TITLE
Agregar el link de registro a la página de meetup en la página de jconfperu 2023

### ISSUE THREAD

**Issue by joedayz** [perujug/jconfperu#5]
Luego de crear el link en meetup hay que ir a la página de https://jconfperu.org/ y agregar el link de registro:

![inscripciones](https://github.com/perujug/jconfperu/assets/1118135/66fa9521-b345-48b1-b834-29aa977a961b)

**Comment by czelabueno** [comment]
Agregado en este PR https://github.com/perujug/jconfperu/pull/9
