### ISSUE TITLE
Crear Reel para la JCONF PERU 2023

### ISSUE THREAD

**Issue by joedayz** [perujug/jconfperu#6]
Hay que crear un reel para tiktok, instagram, facebook y poder compartirlo con miras a obtener mas sponsors.

**Comment by czelabueno** [comment]
@joedayz  Yo tengo ideas y material para usarlo en el reel pero con quien lo trabajo? Mirza?

**Comment by joedayz** [comment]
Tengo otro contacto - David Herrera.

Lo que puedo hacer es presentartelo por facebook y le das la idea. Nos dices, cuanto cobraría y lo sacamos del fondo que tenemos. 

<img width="383" alt="Screenshot 2023-10-17 at 23 53 30" src="https://github.com/perujug/jconfperu/assets/1118135/25ae95d4-e1e1-4358-90db-72f6917c1e08">

**Comment by joedayz** [comment]
Hay que cambiar la dirección :P

**Comment by czelabueno** [comment]
@joedayz me contactare con el disenador, ojala que aun conserve el editable

**Comment by joedayz** [comment]
Cerrado
